### ISSUE TITLE
"=" Ligature error on version 0.12.6

### ISSUE THREAD

**Issue by dionisokan** [be5invis/Sarasa-Gothic#170] opened 2020-06-05 10:09 UTC
Noticed this after installing Sarasa Gothic 0.12.6 (ttc version) using Homebrew:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/19278941/83864395-42077600-a757-11ea-8e4b-aa040a82b38e.png">
Right pointing arrows with `"="` and `">"` seems to be broken, while left pointing arrows are normal. Confirmed there is no such fault in the latest version of Iosevka.

**Comment by be5invis** [comment] 2020-06-05 21:08
Dupe of https://github.com/be5invis/Iosevka/issues/548.
The next release will fix it.

**Closed by be5invis** 2020-06-05 21:08 UTC
