### ISSUE TITLE
Wrong ascent and descent in Android

### ISSUE THREAD

**Issue by CerteKim** [be5invis/Sarasa-Gothic#121] opened 2019-10-30 04:24 UTC
![SC](https://user-images.githubusercontent.com/18364439/67884813-6b3ca400-fb81-11e9-8224-88efc9dafbca.jpg)

**Comment by CyanoHao** [comment] 2019-10-30 05:53
Android adds extra space to some controls for `head.yMin` and `head.yMax`, to avoid trimming on first and last line.

Thus fonts to replace Roboto should have compatible `head.yMin` and `head.yMax` values.

Here is a script to fix these values, using [fonttools](https://github.com/fonttools/fonttools):
```python
import sys
from fontTools.ttLib import TTFont

font = TTFont(sys.argv[1], recalcBBoxes = False)

head_ = font['head']
os2_ = font['OS/2']
upm = head_.unitsPerEm

robotoYMax = 2163
robotoYMin = -555
robotoUpm = 2048
minToMax = (robotoYMax - robotoYMin) / robotoUpm * upm

USE_TYPO_METRICS = 0x80
if os2_.fsSelection & USE_TYPO_METRICS:
	ascender = os2_.sTypoAscender
	descender = os2_.sTypoDescender
else:
	ascender = os2_.usWinAscent
	descender = -os2_.usWinDescent

head_.yMax = round(ascender / (ascender - descender) * minToMax)
head_.yMin = round(descender / (ascender - descender) * minToMax)

font.save(sys.argv[1])
```

Usage:
```bash
pip install fonttools # if necessary
for file in Roboto*.ttf
do
  python fix-metrics.py $file
done
```

**Comment by CerteKim** [comment] 2019-10-30 17:53
I tried to debug ```fix-metrics.py``` and now it works
![SC3](https://user-images.githubusercontent.com/18364439/67884667-32043400-fb81-11e9-99f2-722d009de078.jpg)
...but with some little problem

**Comment by CyanoHao** [comment] 2019-10-30 19:10
It’s U+EE01. To map U+EE01 to colon if not exists:
```python
cmap_ = font['cmap'].getBestCmap()
if 0xEE01 not in cmap_:
	cmap_[0xEE01] = cmap_[0x003A]
```

Updated script:
```python
import sys
from fontTools.ttLib import TTFont

font = TTFont(sys.argv[1], recalcBBoxes = False)

colon = 0x003A
fancyColon = 0xEE01
cmap_ = font['cmap'].getBestCmap()
if fancyColon not in cmap_:
	cmap_[fancyColon] = cmap_[colon]

head_ = font['head']
os2_ = font['OS/2']
upm = head_.unitsPerEm

robotoYMax = 2163
robotoYMin = -555
robotoUpm = 2048
minToMax = (robotoYMax - robotoYMin) / robotoUpm * upm

USE_TYPO_METRICS = 0x80
if os2_.fsSelection & USE_TYPO_METRICS:
	ascender = os2_.sTypoAscender
	descender = os2_.sTypoDescender
else:
	ascender = os2_.usWinAscent
	descender = -os2_.usWinDescent

head_.yMax = round(ascender / (ascender - descender) * minToMax)
head_.yMin = round(descender / (ascender - descender) * minToMax)

font.save(sys.argv[1])
```

**Comment by CerteKim** [comment] 2019-10-31 03:42
The U+EE01 is still a box

**Comment by be5invis** [comment] 2019-11-01 09:50
Sarasa is _never_ designed as an OS replacement font. Its metrics simply follow the latin part.
Closed as by design.

**Closed by be5invis** 2019-11-01 09:50 UTC
