### ISSUE TITLE
建议将压缩文件分成好几个包

### ISSUE THREAD

**Issue by lihaoyu1234** [be5invis/Sarasa-Gothic#119] opened 2019-10-20 03:18 UTC
我的电脑解压时总是提示内存不足……

**Comment by CyanoHao** [comment] 2019-10-20 04:05
7-zip and WinRAR work well on a VM with 2 GiB RAM.

![extract](https://user-images.githubusercontent.com/14287996/67154580-67af4e80-f331-11e9-97ad-f9222a6631dd.png)

**Comment by lihaoyu1234** [comment] 2019-10-20 11:12
……
为什么我的“WinXP + 2GiB RAM + 250 GB 硬盘”提示“内存不足”？
Why does my "WinXP+2GiB RAM+250 GB hard disk" prompt "out of memory"?

**Comment by lihaoyu1234** [comment] 2019-10-20 11:18
……

**Comment by lihaoyu1234** [comment] 2019-10-21 07:07
@be5invis

**Comment by be5invis** [comment] 2019-10-21 07:09
Closed as by design.
The current compression parameters are designed for package size. Reducing it would significantly increase the size of packages -- especially for the TTF package, it would increase the final size by 5 times.

**Closed by be5invis** 2019-10-21 07:09 UTC

**Comment by be5invis** [comment] 2019-10-21 07:12
I can try to reduce the compression parameters to this, that it _may_ reduce the memory use:
`-m0=LZMA:a=0:d=256m:fb=256`

**Comment by lihaoyu1234** [comment] 2019-10-21 09:30
@be5invis 
我的电脑的 RAM 只有 2 GiB，上一个版本（v0.9.1）用的 LZMA:30 压缩，解压时正常。但是这一个版本用的 LZMA:1536m，解压缩时总是失败……

**Comment by be5invis** [comment] 2019-10-21 09:31
I've updated the archives in the releases. Hope that will work.

**Comment by lihaoyu1234** [comment] 2019-10-21 09:33
请问 LZMA:1536m 解压缩时是需要 1536 MiB（即 1.5 GiB）RAM 吗？
