### ISSUE TITLE
更纱黑体autohint版本渲染很慢

### ISSUE THREAD

**Issue by wisenut2009** [be5invis/Sarasa-Gothic#254] opened 2021-08-07 13:57 UTC
更纱黑体autohint版本渲染很慢，打开ttf字体文件时，不同字号的示例文字都是一行一行显示出来的，unhinted版本快很多。有什么办法吗？

**Comment by be5invis** [comment] 2021-08-08 23:23
This is by design because the hint program, being **really complicated**, needs to run to get its clear and sharp display.
Closing as by design.

**Closed by be5invis** 2021-08-08 23:23 UTC
