### ISSUE TITLE
繁體字型顯示錯誤

### ISSUE THREAD

**Issue by tony8077616** [be5invis/Sarasa-Gothic#226] opened 2021-02-08 05:02 UTC
V0.17的下載的載顯示為簡體中文的载
![image](https://user-images.githubusercontent.com/9822340/107177950-07ed2300-6a0e-11eb-9079-66f39e850cce.png)

**Comment by be5invis** [comment] 2021-02-08 06:21
Well it isn’t actually: the 日 part in 車 is squashed due to lack of space.

**Comment by be5invis** [comment] 2021-02-08 06:22
You can try the unhinted version, which is more _accurate_ but less _clear_.

**Comment by be5invis** [comment] 2021-02-08 06:23
Closing as by design.

**Closed by be5invis** 2021-02-08 06:23 UTC
