### ISSUE TITLE
Could you please also consider releasing via Baidu Cloud?

### ISSUE THREAD

**Issue by et2010** [be5invis/Sarasa-Gothic#83] opened 2019-03-24 19:10 UTC
Since the font file is large and the downloading of github file from mainland China is really slow, could you please consider releasing via Baidu Cloud?

**Comment by be5invis** [comment] 2019-03-24 19:12
I do not have Baidu account. Anyone can mirror it.

________________________________
发件人: et2010 <notifications@github.com>
发送时间: Monday, March 25, 2019 3:10:40 AM
收件人: be5invis/Sarasa-Gothic
抄送: Subscribed
主题: [be5invis/Sarasa-Gothic] Could you please also consider releasing via Baidu Cloud? (#83)


Since the font file is large and the downloading of github file from mainland China is really slow, could you please consider releasing via Baidu Cloud?

―

**Comment by et2010** [comment] 2019-03-24 19:27
OK. What about Google cloud?

**Comment by yttrium3** [comment] 2019-03-29 10:09
I've mirrored release 0.8.0 onto an Onedrive account. It can be accessed downloaded from mainland China without any problem (at least for me).
https://ubest-my.sharepoint.com/:f:/g/personal/hyjzhmbvv_onedrive_readmail_net/El63pOQvxldCvya-aqffOEsB6wlOY15rkCwvBR45oE3KTw?e=DQm7Zw

**Comment by be5invis** [comment] 2019-04-22 09:08
Closed as by design.
Mirroring is welcome but I do not have responsibility to do that.

**Closed by be5invis** 2019-04-22 09:08 UTC
