### ISSUE TITLE
优化中国用户体验

### ISSUE THREAD

**Issue by gegb** [be5invis/Sarasa-Gothic#87] opened 2019-04-07 05:27 UTC
由于 Amazon S3 has been GFWed，建议将 releases 页面的字体文件放到 [Coding](https://coding.net)，以提高国内下载速度。

**Comment by wolfan** [comment] 2019-04-18 06:42
coding.net现在要叫腾讯开发者了一没必要放到国内，github就很好。

**Comment by zanxj** [comment] 2019-04-22 09:04
几百兆，下都下不下来，还怎么用

**Comment by be5invis** [comment] 2019-04-22 09:08
Closed as by design.
Mirroring is welcome but I do not have responsibility to do that.

**Closed by be5invis** 2019-04-22 09:08 UTC

**Comment by gegb** [comment] 2019-04-22 12:56
要不我弄一个

**Comment by zanxj** [comment] 2019-04-23 01:43
> 要不我弄一个
可以建个 repository 把每次更新发布的放上面，提供国内用户下载链接

**Comment by zanxj** [comment] 2019-04-23 01:54
> Closed as by design.
> Mirroring is welcome but I do not have responsibility to do that.

This font is mainly for domestic users, should not be a convenient and quick way?Since it is said that there is no responsibility, why should we vigorously promote it on zhihu?
