### ISSUE TITLE
Sarasa in Microsoft Store

### ISSUE THREAD

**Issue by fengmubai** [be5invis/Sarasa-Gothic#122] opened 2019-10-31 02:19 UTC
![image](https://user-images.githubusercontent.com/30486766/67913267-68fd3880-fbc7-11e9-9521-2cda3e93787b.png)
Are you the publisher of the Sarasa in Microsoft Store, or has he obtained your authorization? Here's the link: https://www.microsoft.com/store/productId/9MW0M424NCZ7

**Comment by be5invis** [comment] 2019-10-31 03:43
Dupe of #105
I do not publish that but since the font is in SIL others can publish it to any store/package manager.
Closed.

**Closed by be5invis** 2019-10-31 03:43 UTC
